config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users
  resources :planets do
    resources :orders, only: %i[new create show]
  end
  get "orders", to: "orders#index", as: :orders
  root to: 'planets#index'
  resources :articles, except: :index
  resources :about, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :planet
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  validates :name, :galaxy, :price, :size, :temperature, :pressure, presence: true
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :galaxy, :price, :size, :temperature, :pressure ],
    associated_against: {
      user: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }
  def bought!
    self.update_attribute :bought, true
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :planets, dependent: :destroy
  has_many :orders, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_action :pundit_policy_scoped?, only: :index

  def index; end

  private

  def pundit_policy_scoped?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name photo])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = policy_scope(Order)
  end

  def new
    @order = Order.new
    authorize(@order)
    @planet = Planet.find(params[:planet_id])
  end

  def create
    @order = Order.new
    authorize(@order)
    @order.user = current_user
    @planet = Planet.find(params[:planet_id])
    @order.planet = @planet
    @planet.bought!
    if @order.save
      redirect_to planets_path
    else
      render :new
    end
  end

  def show
    authorize(@order)
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:planet_id)
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :pundit_policy_scoped?, only: :index

  def index
    if params[:query]
      @planets = Planet.global_search(params[:query])
    else
      @planets = policy_scope(Planet)
    end
  end

  def new
    @planet = Planet.new
    authorize(@planet)
  end

  def create
    @planet = Planet.new(planet_params)
    authorize(@planet)
    @planet.user = current_user
    @planet.save
    redirect_to planets_path
  end

  def show
    @planet = Planet.find(params[:id])
    authorize(@planet)
  end

  def edit
    @planet = Planet.find(params[:id])
    authorize(@planet)
  end

  def update
    @planet = Planet.find(params[:id])
    authorize(@planet)
    params[:planet][:bought] = false if params[:planet][:bought] == "false"
    if @planet.update(planet_params)
      if params[:planet][:bought] == false
        redirect_to planets_path
      else
        redirect_to planet_path(@planet)
      end
    else
      render 'edit'
    end
  end

  def destroy
    @planet = Planet.find(params[:id])
    authorize(@planet)
    @planet.destroy
    redirect_to planets_path
  end

  def planet_params
    params.require(:planet).permit(:name, :galaxy, :price, :size, :temperature, :pressure, :image, :bought, :description)
  end

  private

  def pundit_policy_scoped?
    true
  end
end

app/controllers/transactions_controller TROCAR POR ORDERS.rb
class TransactionsController < ApplicationController
  def new
  end

  def create
  end

  def show
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
  end

  def create
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="abouth1">
  <h1>About Us</h1>
</div>
  <div class="galaxy">
    <h2>In a Galaxy Far, Far Away...</h2>
  </div>
  <div class="about">
    <p>Just kidding. Since the earthlings are breaking technological barriers with their space missions in recent times,
     we decided to create a team that seeks to facilitate the negotiation of the most diverse types of planets.
     Perhaps our team is composed of Cosmic Entities? Who knows?</p>
  </div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PLANETARIUM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <style> @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap'); </style>
    <style>@import url('https://fonts.googleapis.com/css2?family=Raleway:wght@600&family=Roboto:wght@300&display=swap');</style>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Your planets</h1>
<div class="cards">
  <% @orders.each_with_index do |order, index| %>
    <%= link_to planet_path(order.planet) do %>
      <div class="card-trip">
        <img src=<%= order.planet.image ? order.planet.image : "https://source.unsplash.com/random/?planet" %> alt="">
        <div class="card-trip-infos">
          <div>
            <h2><%= order.planet.name %></h2>
          </div>
          <h2 class="card-trip-pricing">US$ <%= order.planet.price %></h2>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/orders/new.html.erb
<h2>Do you really want to buy <strong><%= @planet.name %></strong> for US$ <%= @planet.price %>?</h2>
<%= simple_form_for [@planet, @order] do |f| %>
  <div class="buy-button">
    <%= f.submit 'Yes', class: 'btn btn-light btn-lg'%>
    <%= link_to 'No', planet_path(@planet), class: 'btn btn-light btn-lg'  %>
  </div>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
<div class="container">
<h1>Planets on Sale</h1>
<ul>
<%= @planets.each do |planet| %>
<li><%= link_to planet.name, planet_path(planet) %></li>
<%= end %>
</ul>
</div>

app/views/planets/_form.html.erb
<% if params[:sell] == "true" %>
  <%= simple_form_for(planet) do |f| %>
    <%= f.input :price %>
    <%= f.input :bought, input_html: { value: false }, as: :hidden %>
    <%= f.submit class: "btn btn-light" %>
  <% end %>
<% else %>
  <%= simple_form_for(planet) do |f| %>
    <%= f.input :name %>
    <%= f.input :galaxy %>
    <%= f.input :price %>
    <%= f.input :size  %>
    <%= f.input :temperature %>
    <%= f.input :pressure %>
    <%= f.input :image %>
    <%= f.input :description %>
    <%= f.submit class: "btn btn-light" %>
  <% end %>
<% end %>

app/views/planets/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="planet-form">
        <h1><%= params[:sell] == "true" ? "Set your price": "Edit Planet"%></h1>
        <div class="mt-3">
          <%= render "form", planet: @planet %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/planets/index.html.erb
<div class="container">

<h1>PLANETARIUM</h1>
<h2><strong>Welcome aboard!</strong></h2>
<h4><strong>but if you're <strong>Galactus</strong>... please buy before you eat. Thanks :)</strong></h4>



<div class="search-bar col-sm-8 offset-sm-2">
  <%= form_tag planets_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a Planet"
    %>
    <div class="teste">
      <%= submit_tag "Search", class: "btn btn-light"  %>
    </div>
  <% end %>
</div>

<h3><strong>Planets on Sale</strong></h3>

<div class="cards">
<% if @planets.present? %>
  <% @planets.each_with_index do |planet, index| %>
    <%= link_to planet_path(planet) do %>
      <div class="card-trip">
        <img src=<%= planet.image ? planet.image : "https://source.unsplash.com/random/?planet" %> alt="">
        <div class="card-trip-infos">
          <div>
            <h2><%= planet.name.truncate(30) %></h2>
          </div>
          <h2 class="card-trip-pricing">US$ <%= planet.price %></h2>
        </div>
      </div>
    <% end %>
  <% end %>
  <% else %>
    <h3> No planet found :( </h3>
  <% end %>
</div>
<br>
<div class="create-button">
  <%= link_to 'Create Planet', new_planet_url, class: 'btn btn-light btn-lg'  %>
</div>
<footer>
  <p><strong>Coming Soon...</strong></p>
  <p><strong>Protect Yourself Against Space Invaders!</strong></p>
  <br>
  <img class="space-invader" src="https://files.tecnoblog.net/wp-content/uploads/2012/06/space-invader.jpg" alt="">
</footer>

</div>

app/views/planets/new.html.erb
<h1>Create a new planet</h1>
<div class="container">
  <%= render 'form', planet: @planet %>
</div>

app/views/planets/show.html.erb
<div class="container-buy container">
  <h1><%= @planet.name %></h1>
  <img src=<%= @planet.image ? @planet.image : "https://source.unsplash.com/random/?planet" %> alt="" style="height: 300px">
  <div class="the-list">
    <ul>
      <li><strong>Galaxy:</strong> <%=@planet.galaxy%></li>
      <li><strong>Price:</strong> US$ <%=@planet.price%> </li>
      <li><strong>Size:</strong> <%=@planet.size%> km²</li>
      <li><strong>Temperature:</strong> <%=@planet.temperature%> °C </li>
      <li><strong>Pressure:</strong> <%=@planet.pressure%> atm</li>
      <% if @planet.description.present? %>
      <li><strong>Description:</strong> <%=@planet.description%></li>
      <% end %>

    </ul>
  </div>

  <% unless policy(@planet).order? %>
    <div class="buy-planet">
      <%= link_to 'Buy Planet', new_planet_order_path(@planet), class: 'btn btn-light'  %>
    </div>
  <% end %>

  <% if policy(@planet).sell? %>
    <div class="sell-planet">
      <%= link_to 'Sell Planet', edit_planet_path(@planet, sell: true), class: 'btn btn-light'  %>

  <% end %>

  <% if policy(@planet).edit? %>
    <%= link_to 'Edit Planet', edit_planet_path(@planet), class: 'btn btn-light' %>
  <% end %>

  <% if policy(@planet).destroy? %>
    <%= link_to 'Delete Planet', planet_path(@planet), method: :delete, class: 'btn btn-danger' %>
  <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Foguete1.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Planets", orders_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "About Us", about_index_path, class: "nav-link" %>
          </li>

          <% if current_user %>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag(current_user.photo.key, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "About Us", about_index_path, class: "nav-link" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</div>